name: my_env_API
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - fastapi
      - uvicorn
      - mlflow
